package com.theladders.solid.dip;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SuggestedArticleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public SuggestedArticleExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected abstract static class GeneratedCriteria {
        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithSingleValue = new ArrayList<>();
            criteriaWithListValue = new ArrayList<>();
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        public Criteria andSubscriberIdEqualTo(Integer value) {
            addCriterion("subscriber_id =", value, "subscriberId");
            return (Criteria) this;
        }

        public Criteria andSuggestedArticleSourceIdEqualTo(Integer value) {
            addCriterion("suggested_article_source_id =", value, "suggestedArticleSourceId");
            return (Criteria) this;
        }

        public Criteria andSuggestedArticleStatusIdIn(List<Integer> values) {
            addCriterion("suggested_article_status_id in", values, "suggestedArticleStatusId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table suggested_article
     *
     * @mbggenerated do_not_delete_during_merge Fri Dec 03 17:06:47 EST 2010
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}